import type { BookingRecord } from '../../core/store/types.js';
import type { AppContext } from '../../core/context.js';
import { createBookingToken } from '../../core/calendar/index.js';
import { env } from '../../config/env.js';

export class BookingService {
  constructor(private readonly context: AppContext) {}

  async prepareBookingOffer(
    leadId: string,
    ownerUserId?: string | null
  ): Promise<{ booking: BookingRecord; slots: Array<{ start: string; end: string; timezone: string }> }> {
    const lead = await this.context.store.leads.findById(leadId, ownerUserId);
    if (!lead) {
      throw new Error(`Lead ${leadId} not found`);
    }

    const existing = await this.context.store.bookings.listBookings(leadId);
    const pending = existing.find((booking) => booking.status === 'pending');
    if (pending) {
      return {
        booking: pending,
        slots: [
          {
            start: pending.slotStart.toISOString(),
            end: pending.slotEnd.toISOString(),
            timezone: pending.timezone
          }
        ]
      };
    }

    const slots = await this.context.calendar.findAvailability({
      timezone: env.CALENDAR_TIMEZONE,
      slotMinutes: env.BOOKING_SLOT_MINUTES,
      windowDays: env.BOOKING_WINDOW_DAYS,
      count: 5
    });

    const slot = slots[0];
    if (!slot) {
      throw new Error('No booking slots available');
    }

    const token = createBookingToken();
    const booking = await this.context.store.bookings.createBooking({
      leadId,
      bookingToken: token,
      slotStart: new Date(slot.start),
      slotEnd: new Date(slot.end),
      timezone: slot.timezone,
      meetingLink: this.context.calendar.generateBookingLink(token),
      provider: this.context.calendar.provider,
      status: 'pending',
      notes: `Autogenerated booking offer for ${lead.firstName ?? 'lead'}`,
      metadata: {
        slots,
        autoGenerated: true
      }
    });

    await this.context.store.leads.addActivity(leadId, {
      type: 'booking.offer',
      channel: 'note',
      title: 'Booking offer prepared',
      body: `Generated booking link ${booking.meetingLink}`,
      metadata: {
        bookingToken: token,
        slotStart: booking.slotStart.toISOString(),
        slotEnd: booking.slotEnd.toISOString()
      }
    });

    return { booking, slots };
  }

  async confirmBooking(token: string, notes?: string, ownerUserId?: string | null): Promise<BookingRecord> {
    const booking = await this.context.store.bookings.findByToken(token);
    if (!booking) {
      throw new Error(`Booking token ${token} not found`);
    }

    if (booking.status === 'confirmed') {
      return booking;
    }

    const lead = await this.context.store.leads.findById(booking.leadId, ownerUserId);
    if (!lead) {
      throw new Error(`Lead ${booking.leadId} not found`);
    }

    const confirmed = await this.context.store.bookings.updateBooking(booking.id, {
      status: 'confirmed',
      notes: notes ?? booking.notes,
      metadata: {
        ...booking.metadata,
        confirmedAt: new Date().toISOString()
      }
    });

    await this.context.store.leads.update(booking.leadId, {
      status: 'booked',
      bookedAt: new Date(),
      nextFollowUpAt: null
    });

    await this.context.store.leads.addActivity(booking.leadId, {
      type: 'booking.confirmed',
      channel: 'note',
      title: 'Meeting booked',
      body: `Meeting confirmed for ${confirmed.slotStart.toISOString()}`,
      metadata: {
        bookingToken: confirmed.bookingToken,
        meetingLink: confirmed.meetingLink
      }
    });

    await this.context.store.analytics.createEvent({
      leadId: booking.leadId,
      type: 'booking.confirmed',
      value: 1,
      metadata: {
        bookingToken: confirmed.bookingToken
      }
    });

    return confirmed;
  }

  async listBookings(leadId: string, ownerUserId?: string | null): Promise<BookingRecord[]> {
    if (ownerUserId !== undefined) {
      const lead = await this.context.store.leads.findById(leadId, ownerUserId);
      if (!lead) {
        return [];
      }
    }
    return this.context.store.bookings.listBookings(leadId);
  }

  async getBookingByToken(token: string, ownerUserId?: string | null): Promise<BookingRecord> {
    const booking = await this.context.store.bookings.findByToken(token);
    if (!booking) {
      throw new Error(`Booking token ${token} not found`);
    }
    if (ownerUserId !== undefined) {
      const lead = await this.context.store.leads.findById(booking.leadId, ownerUserId);
      if (!lead) {
        throw new Error(`Booking token ${token} not found`);
      }
    }
    return booking;
  }
}
